name: deploy-gh-pages
run-name: 2022_01-ci-di-my-angular-NTPxz
on:
  push:
    branches:
      - "ci"
jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secret.PUSH_MAIN }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: |
          git config --global user.email "{{ github.event.pusher.email }}"
          git config --global user.name "{{ github.actor }}"
      - run: npm install -g yarn
      - run: npm install
      - run: PUBLIC_URL=/${{ github.event.repository.name }} npm run build
      - run: |
          git remote set-url origin \
          https://git:${{ github.token }}@github.com/${{ github.repository }}.git
      - run: |
          npm ci
      - run: npm run test
      - run: |
          git fetch --unshallow
          git checkout main
          git merge ci 
          git push
  deploy-gh-pages1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: |
          git config --global user.email "{{ github.event.pusher.email }}"
          git config --global user.name "{{ github.actor }}"
      - run: npm install -g
      - run: yarn install --frozen-lockfile
      - run: npx ng build --configuration=production --base-href="/${{ github.event.repository.name }}" yarn run build
      - run: |
          cd ./build
          git init -b gh-pages
          git remote add -t gh-pages origin \
          https://git:${{ github.token }}@github.com/${{ github.repository }}.git
          git fetch -u origin gh-pages:gh-pages 
          git add . 
          git commit -m "${{ github.actor }} deploy"
          git push origin gh-pages -f 
          cd ..
